### ISSUE TITLE
B Format Convolution Reverb Crashes Ableton when added

### ISSUE THREAD

**Issue by JonathanRowden** [EnvelopSound/EnvelopForLive#50] opened 2018-12-20 22:21 UTC
B Format Convolution Reverb Crashes Ableton when added as a single instance or more, regardless of whether there is a source panner or other device on the given track. Appeared randomly, no changes other than regular Windows/Java/GPU driver updates. Sometimes, we get a "a serious problem has occurred" message, in which case the project file becomes corrupted and will no longer open after crash.

**Comment by JonathanRowden** [comment] 2018-12-21 02:56
Was able to get them working but only by the following workflow:
Create Track > Add B Format Conv Verb > Add E4L Device (source panner etc) > Adjust Routing/Chain

However, after doing this for about 6 tracks/instances Ableton crashes.

**Comment by JonathanRowden** [comment] 2019-01-01 01:09
Still no resolution. Have made sure all installs are 64-bit and followed similar procedures to people having crashing issues with other M4L devices. Has anyone looked into this yet? We are running Windows 10.

**Comment by JonathanRowden** [comment] 2019-01-01 01:51
Update - tried opening the devices within Max Console and B format Convolution Reverb crashes Max.

**Comment by ramagottfried** [comment] 2019-01-01 11:03
Hi Jonathan, happy new year!
thanks for your testing -- I don't have a Windows 10 machine on hand at the moment, but I'll take a look soon. Are there any crash logs produced?

**Comment by JonathanRowden** [comment] 2019-01-01 21:33
Hi! Crash logs only from Ableton, yes. Want to see them?

**Comment by ramagottfried** [comment] 2019-01-02 09:49
yes sure, I'm assuming they're all the similar?

**Comment by JonathanRowden** [comment] 2019-01-03 23:03
[Ableton Crash Report 2019-01-03 150057 Live 10.0.5.zip](https://github.com/EnvelopSound/EnvelopForLive/files/2725553/Ableton.Crash.Report.2019-01-03.150057.Live.10.0.5.zip)

Heres the crash report. Added a B Format Reverb and it crashed my program. Typically, after a single crash, the project has more and more issues and at times it becomes totally corrupted (wont successfully open).

**Comment by JonathanRowden** [comment] 2019-01-03 23:07
Yeah the project wont open now. 4 hours of mixing and goodbye... Thanks for looking into this Rama the workflow has become unusable.

**Comment by JonathanRowden** [comment] 2019-01-03 23:11
![screenshot 1](https://user-images.githubusercontent.com/46035305/50666480-bf7af580-0f69-11e9-878f-b25f66da374b.png)

Here is what happens. I have reinstalled EVERYTHING fresh and gone through Max reset instructions and its still happening. Just adding context

**Comment by mcslee** [comment] 2019-01-07 20:37
Just noting a possible source of issue here - discussing with @ramagottfried and one common piece between the Ableton Convolution Reverb and the E4L device is that both use the Alex Harker convolution externals. Jonathan - you mentioned that thread about other users seeing crashes on Windows 10 with the stock Ableton Convolution Reverb. It's possible that something inside that library is the common denominator that is having issues with either the latest Windows 10 or some particular machine configuration.

Is the standard Ableton Convolution Reverb working okay for you at this point? Does that also crash your system?

**Comment by JonathanRowden** [comment] 2019-01-07 21:53
I just opened the Ableton convolution reverbs in Max and they didn't crash it. E4L one still crashes it though (just testing again)

**Comment by ramagottfried** [comment] 2019-01-18 08:04
ok good luck!
p.s. the E4L devices won't really work running in Max, outside of MaxForLive, since they send audio via the M4L API, but anyway it shouldn't crash. 

I'm going to close this issue since we can't reproduce the crash, which makes me think it's something to do with either permissions or some other system specific configuration.

**Closed by ramagottfried** 2019-01-18 08:04 UTC

**Comment by JonathanRowden** [comment] 2019-01-18 09:30
Yeah I know they don’t run - but the crashing is consistent. It’s only this B format convolution. So frustrating. But I guess we will see what Cycling says. Wouldn’t hurt to know if there’s a setting that will fuck your productivity up. 

Thanks again!

Jonathan Rowden 
CEO / Co-Founder 
Zero System Immersive Music 
www.thezerosystem.com
www.thezerosystem.bandcamp.com
All Content & IP Copyright 2019 Zero System LLC
All Rights Reserved

**Comment by JonathanRowden** [comment] 2019-02-09 06:33
Not that you guys are concerned about it anymore, but we’ve had an outside tech come by and he examined all the crash logs, and it would seem there is a bug somewhere between ableton and max that is causing an issue with the two communicating when opening a convolution reverb. I’ll be moving on to Cycling and/or Ableton but I want you to be aware that it isn’t some system administrator setting issue. 

Jonathan Rowden 
CEO / Co-Founder 
Zero System Immersive Music 
www.thezerosystem.com
www.thezerosystem.bandcamp.com
All Content & IP Copyright 2019 Zero System LLC
All Rights Reserved

**Comment by ramagottfried** [comment] 2019-02-09 08:37
Ok, good luck, let us know if you can isolate the problem

**Comment by JonathanRowden** [comment] 2019-02-10 03:49
I’ll try to update you if I find it. So far the bug is replicating on a brand new hard drive and new install of windows with new user and everything. Crash seems to report points towards a communication issues between Ableton and Max. 

Jonathan Rowden 
CEO / Co-Founder 
Zero System Immersive Music 
www.thezerosystem.com
www.thezerosystem.bandcamp.com
All Content & IP Copyright 2019 Zero System LLC
All Rights Reserved
