### ISSUE TITLE
Only two input channels pass through HOA Scope

### ISSUE THREAD

**Issue by kobashi** [EnvelopSound/EnvelopForLive#73] opened 2021-02-27 06:02 UTC
Hi,

Only two input channels pass through HOA Scope in Live11.
16 chain -> HOA Scope -> (stereo)

like this.
https://twitter.com/_kobashi/status/1365537304723394560

**Comment by ramagottfried** [comment] 2021-02-27 07:51
hi @kobashi, I just tested on my system with Live 11 trial, and the channels seem to be passing through as expected.  but please let us know your operating system, and if there are a specific set of steps necessary to reproduce the issue, and we can test it. 

<img width="1065" alt="Screen Shot 2021-02-27 at 08 45 08" src="https://user-images.githubusercontent.com/2264377/109381061-4d4b9480-78d8-11eb-84dc-a3db4f31b1fb.png">

**Comment by mcslee** [comment] 2021-02-28 03:44
This is also working okay for my system on Live 10. One thing you can try, if you click on the yellow text for the device that does not seem to be passing audio properly, this will re-set the channel routing. Sometimes this will fix a channel audio routing problem.

Showing where to click in the red box here. You could try this on all the devices in the chain to see if it helps.

<img width="1069" alt="Screen Shot 2021-02-27 at 7 42 29 PM" src="https://user-images.githubusercontent.com/597850/109407242-05f2f180-7934-11eb-9d49-589736e7704e.png">

**Comment by kobashi** [comment] 2021-02-28 12:33
thank you for comments.

my system:
processor Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (for mobile pc)
RAM 16GB
OS Windows 10 Pro (20H2)

It's not working on Live10 and Live11.
![SharedScreenshot](https://user-images.githubusercontent.com/2777154/109418492-f941cc80-7a0b-11eb-8b44-9517485a5b5d.jpg)

and E4L HOA Scope works on my system too that case Source Panner -> Scope -> HOA Transform.

**Comment by mcslee** [comment] 2021-03-01 22:21
Ah, I see the issue now. I believe this problem is a bug with our code, it seems to be caused because the B-Format Sampler is actually a Max Instrument, not a Max Audio Effect. This is causing an issue with the E4L routing code, which is counting the audio effect devices on the channel when building up the routing assignments. So it works okay when the chain is all Max Audio Effects (e.g. in the Panner case) - but not the Sampler case.

Thank you for identifying this issue! I will look into a fix.

**Comment by mcslee** [comment] 2021-03-01 22:22
<img width="856" alt="Screen Shot 2021-03-01 at 2 21 50 PM" src="https://user-images.githubusercontent.com/597850/109566975-7bc49d80-7a99-11eb-8510-288a64f0e98c.png">

I am documenting here the most simple case of the issue - which is just using E4L Meter. The issue is not specific to which E4L Audio Effects come in the chain - it's in the generic routing logic.

**Comment by mcslee** [comment] 2021-03-02 17:22
This bug has been fixed by: https://github.com/EnvelopSound/EnvelopForLive/commit/4f8cb637dd58a1574d4be299adf242772b003ec9

This will be included in the next release of E4L - FYI we are planning to release E4L 11 within the next couple months, which should be compatible with both Live 10 and 11.

In the meantime, if you want to use this change, you can work off the Developers version of E4L with the instructions here:
https://github.com/envelopsound/EnvelopForLive#for-developers-clone-repository

Thanks again for finding and reporting this issue!

**Closed** 2022-02-02 20:51 UTC
Labels: fixed
